/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Frootz - Doces & Salgados API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";
/**
 * @summary Health check
 */
export declare const HealthCheckResponse: zod.ZodObject<{
    status: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    status: string;
}, {
    status: string;
}>;
/**
 * @summary Admin login
 */
export declare const AdminLoginBody: zod.ZodObject<{
    username: zod.ZodString;
    password: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    username: string;
    password: string;
}, {
    username: string;
    password: string;
}>;
export declare const AdminLoginResponse: zod.ZodObject<{
    username: zod.ZodString;
    loggedIn: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    username: string;
    loggedIn: boolean;
}, {
    username: string;
    loggedIn: boolean;
}>;
/**
 * @summary Get store settings
 */
export declare const GetStoreSettingsResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    companyName: zod.ZodString;
    cnpj: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappNumber: zod.ZodString;
    phoneAdditional: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappMessage: zod.ZodString;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    companyName: string;
    whatsappNumber: string;
    whatsappMessage: string;
    updatedAt: Date;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    phoneAdditional?: string | null | undefined;
}, {
    id: number;
    companyName: string;
    whatsappNumber: string;
    whatsappMessage: string;
    updatedAt: Date;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    phoneAdditional?: string | null | undefined;
}>;
/**
 * @summary Update store settings (admin only)
 */
export declare const UpdateStoreSettingsBody: zod.ZodObject<{
    companyName: zod.ZodOptional<zod.ZodString>;
    cnpj: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappNumber: zod.ZodOptional<zod.ZodString>;
    phoneAdditional: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappMessage: zod.ZodOptional<zod.ZodString>;
}, "strip", zod.ZodTypeAny, {
    companyName?: string | undefined;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    whatsappNumber?: string | undefined;
    phoneAdditional?: string | null | undefined;
    whatsappMessage?: string | undefined;
}, {
    companyName?: string | undefined;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    whatsappNumber?: string | undefined;
    phoneAdditional?: string | null | undefined;
    whatsappMessage?: string | undefined;
}>;
export declare const UpdateStoreSettingsResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    companyName: zod.ZodString;
    cnpj: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    logoUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappNumber: zod.ZodString;
    phoneAdditional: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    whatsappMessage: zod.ZodString;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    companyName: string;
    whatsappNumber: string;
    whatsappMessage: string;
    updatedAt: Date;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    phoneAdditional?: string | null | undefined;
}, {
    id: number;
    companyName: string;
    whatsappNumber: string;
    whatsappMessage: string;
    updatedAt: Date;
    cnpj?: string | null | undefined;
    logoUrl?: string | null | undefined;
    phoneAdditional?: string | null | undefined;
}>;
/**
 * @summary Get current admin session
 */
export declare const GetMeResponse: zod.ZodObject<{
    username: zod.ZodString;
    loggedIn: zod.ZodBoolean;
}, "strip", zod.ZodTypeAny, {
    username: string;
    loggedIn: boolean;
}, {
    username: string;
    loggedIn: boolean;
}>;
/**
 * @summary List all categories
 */
export declare const ListCategoriesResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    slug: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    slug: string;
    createdAt: Date;
}, {
    id: number;
    name: string;
    slug: string;
    createdAt: Date;
}>;
export declare const ListCategoriesResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    slug: zod.ZodString;
    createdAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    name: string;
    slug: string;
    createdAt: Date;
}, {
    id: number;
    name: string;
    slug: string;
    createdAt: Date;
}>, "many">;
/**
 * @summary Create a category
 */
export declare const CreateCategoryBody: zod.ZodObject<{
    name: zod.ZodString;
    slug: zod.ZodString;
}, "strip", zod.ZodTypeAny, {
    name: string;
    slug: string;
}, {
    name: string;
    slug: string;
}>;
/**
 * @summary List all products
 */
export declare const ListProductsQueryParams: zod.ZodObject<{
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    featured: zod.ZodOptional<zod.ZodNullable<zod.ZodBoolean>>;
    onPromotion: zod.ZodOptional<zod.ZodNullable<zod.ZodBoolean>>;
}, "strip", zod.ZodTypeAny, {
    categoryId?: number | null | undefined;
    featured?: boolean | null | undefined;
    onPromotion?: boolean | null | undefined;
}, {
    categoryId?: number | null | undefined;
    featured?: boolean | null | undefined;
    onPromotion?: boolean | null | undefined;
}>;
export declare const ListProductsResponseItem: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    onPromotion: zod.ZodBoolean;
    featured: zod.ZodBoolean;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}>;
export declare const ListProductsResponse: zod.ZodArray<zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    onPromotion: zod.ZodBoolean;
    featured: zod.ZodBoolean;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}>, "many">;
/**
 * @summary Create a product (admin only)
 */
export declare const CreateProductBody: zod.ZodObject<{
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    onPromotion: zod.ZodOptional<zod.ZodBoolean>;
    featured: zod.ZodOptional<zod.ZodBoolean>;
    active: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name: string;
    price: number;
    categoryId?: number | null | undefined;
    featured?: boolean | undefined;
    onPromotion?: boolean | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    active?: boolean | undefined;
}, {
    name: string;
    price: number;
    categoryId?: number | null | undefined;
    featured?: boolean | undefined;
    onPromotion?: boolean | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    active?: boolean | undefined;
}>;
/**
 * @summary Get product stats for dashboard
 */
export declare const GetProductStatsResponse: zod.ZodObject<{
    total: zod.ZodNumber;
    onPromotion: zod.ZodNumber;
    featured: zod.ZodNumber;
    active: zod.ZodNumber;
    byCategory: zod.ZodArray<zod.ZodObject<{
        categoryName: zod.ZodString;
        count: zod.ZodNumber;
    }, "strip", zod.ZodTypeAny, {
        categoryName: string;
        count: number;
    }, {
        categoryName: string;
        count: number;
    }>, "many">;
}, "strip", zod.ZodTypeAny, {
    featured: number;
    onPromotion: number;
    active: number;
    total: number;
    byCategory: {
        categoryName: string;
        count: number;
    }[];
}, {
    featured: number;
    onPromotion: number;
    active: number;
    total: number;
    byCategory: {
        categoryName: string;
        count: number;
    }[];
}>;
/**
 * @summary Get a product by ID
 */
export declare const GetProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const GetProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    onPromotion: zod.ZodBoolean;
    featured: zod.ZodBoolean;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}>;
/**
 * @summary Update a product (admin only)
 */
export declare const UpdateProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
export declare const UpdateProductBody: zod.ZodObject<{
    name: zod.ZodOptional<zod.ZodString>;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodOptional<zod.ZodNumber>;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    onPromotion: zod.ZodOptional<zod.ZodBoolean>;
    featured: zod.ZodOptional<zod.ZodBoolean>;
    active: zod.ZodOptional<zod.ZodBoolean>;
}, "strip", zod.ZodTypeAny, {
    name?: string | undefined;
    categoryId?: number | null | undefined;
    featured?: boolean | undefined;
    onPromotion?: boolean | undefined;
    description?: string | null | undefined;
    price?: number | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    active?: boolean | undefined;
}, {
    name?: string | undefined;
    categoryId?: number | null | undefined;
    featured?: boolean | undefined;
    onPromotion?: boolean | undefined;
    description?: string | null | undefined;
    price?: number | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    active?: boolean | undefined;
}>;
export declare const UpdateProductResponse: zod.ZodObject<{
    id: zod.ZodNumber;
    name: zod.ZodString;
    description: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    price: zod.ZodNumber;
    originalPrice: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    imageUrl: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    categoryId: zod.ZodOptional<zod.ZodNullable<zod.ZodNumber>>;
    categoryName: zod.ZodOptional<zod.ZodNullable<zod.ZodString>>;
    onPromotion: zod.ZodBoolean;
    featured: zod.ZodBoolean;
    active: zod.ZodBoolean;
    createdAt: zod.ZodDate;
    updatedAt: zod.ZodDate;
}, "strip", zod.ZodTypeAny, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}, {
    id: number;
    updatedAt: Date;
    name: string;
    createdAt: Date;
    featured: boolean;
    onPromotion: boolean;
    price: number;
    active: boolean;
    categoryId?: number | null | undefined;
    description?: string | null | undefined;
    originalPrice?: number | null | undefined;
    imageUrl?: string | null | undefined;
    categoryName?: string | null | undefined;
}>;
/**
 * @summary Delete a product (admin only)
 */
export declare const DeleteProductParams: zod.ZodObject<{
    id: zod.ZodNumber;
}, "strip", zod.ZodTypeAny, {
    id: number;
}, {
    id: number;
}>;
//# sourceMappingURL=api.d.ts.map